In [1]:
import numpy as np #importing the NumPy library and alias it as np

In [2]:
l1 = [1,"abc",2.5]
l1

[1, 'abc', 2.5]

In [3]:
type(l1[1])

str

In [4]:
#create numpy 1-Darray

arr = np.array([10,5,20,15])
arr

array([10,  5, 20, 15])

In [5]:
#create numpy 1Darray

mix_arr = np.array([10,20,3.5,'hello'])
#NumPy converts all the elemenets into string (Unicode) data type
mix_arr

array(['10', '20', '3.5', 'hello'], dtype='<U32')

In [6]:
type(mix_arr) # central data structure is the ndarray (short for N-dimensional array)

numpy.ndarray

In [7]:
type(mix_arr[1])

numpy.str_

In [9]:
#multi-dimensional array

m = np.array ([[1,2,3],
               [4,5,6]]) #2rows,3 cols,Size: 2X3
m

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
type(m[0][1])

numpy.int64

In [13]:
m[0][1]

np.int64(2)

In [14]:
#multi-dimensional array

m1 = np.array([[1,2,3],
             [4,5,6]], np.int32)
#This specifies the data type of the elements in the array.
#In this case, the data type is int32, which means the elements will be 32-bit signed integers.
m1

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [15]:
type(m1)

numpy.ndarray

In [16]:
import  numpy as np
myarr=np.array([[1,2,3,4],
                [1,2,5,6],
                [1,3,4,5]])#3X4
print(myarr)


[[1 2 3 4]
 [1 2 5 6]
 [1 3 4 5]]


In [17]:
print(np.max(myarr)) #finding max value from matrix,#6
print(np.min(myarr)) #finding min value from matrix,#1
print(np.sum(myarr)) #calculating sum of all the values of matrix #37
print(np.max(myarr,axis=0)) #finding max value column wise #[1,3,5,6]
print(np.min(myarr,axis=0)) #fining min value column wise  #[1,2,3,4]
print(np.sum(myarr,axis=0)) #calculating sum column wise # [3,7,12,15]
print(np.max(myarr,axis=1)) #finding max value row wise #[4,6,5]
print(np.min(myarr,axis=1)) #fining min value row wise #[1,1,1]
print(np.sum(myarr,axis=1)) #calculating sum row wise #[10,14,13]
print(myarr.shape) #no. of rows and columns #3X4
print(myarr.size) #total no. of elements #12

6
1
37
[1 3 5 6]
[1 2 3 4]
[ 3  7 12 15]
[4 6 5]
[1 1 1]
[10 14 13]
(3, 4)
12


In [18]:
print(myarr.flatten()) #combines all the elements of array

[1 2 3 4 1 2 5 6 1 3 4 5]


In [21]:
reshape_arr=myarr.reshape(3,4)
print(reshape_arr)


[[1 2 3 4]
 [1 2 5 6]
 [1 3 4 5]]


In [22]:
print(myarr.T) #Transpose matrix
#[[1 2 3 4]
 #[1 2 5 6]
 #[1 3 4 5]]

[[1 1 1]
 [2 2 3]
 [3 5 4]
 [4 6 5]]


In [23]:
print(myarr)

[[1 2 3 4]
 [1 2 5 6]
 [1 3 4 5]]


In [24]:
print(myarr[0:2,1:])#Index slicing
#Rows : 0:2 -->[1 2 3 4]
              # [1 2 5 6]
#col : 1: --> [2 3 4]
           #   [2 5 6]
            #  [3 4 5]

[[2 3 4]
 [2 5 6]]


In [25]:
print(myarr[2,:])#select row at index 2

[1 3 4 5]


In [26]:
#[[1 2 3 4]
# [1 2 5 6]
# [1 3 4 5]]
print(myarr[:1,2])
#The first index (:1) applies to rows.
#The second index (2) applies to columns.

[3]


In [27]:
newarr=np.ones((2,3)) #by default data type "float"
#np.ones() is a NumPy function used to create a new array filled with ones.
print(newarr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
newarr=np.ones((2,3),dtype = np.int32)
# NumPy will create an array where all the elements will be 32-bit integers (int32).
print(newarr)

[[1 1 1]
 [1 1 1]]


In [30]:
newarr1=np.empty((2,2),dtype = np.int32)
#np.empty() is a function in NumPy that creates a new array of the specified shape and type, but without initializing its values
#dtype: Specifies the data type of the elements that is integer
newarr1
#will contain uninitialized random data -whatever happens to be in memory at the time

array([[0, 0],
       [0, 0]], dtype=int32)

In [31]:
n_eye = np.eye(6,dtype=np.int32)#6 rows & 6 cols
#np.eye() is a function in NumPy used to create a 2D identity matrix. An identity matrix is a square matrix with 1's on the main diagonal and 0's everywhere else
n_eye

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int32)

In [32]:
even = np.arange(2,26,2)
#np.arange(start, stop, step) generates an array with a range of values starting from start, up to (but not including) stop
#start: The first value in the array (inclusive).
#stop: The end of the range (exclusive). The array will stop before reaching this value.
#step: The difference between consecutive values in the array (this is the increment)
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [33]:
f = np.arange(1,3,0.2)
f

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [34]:
np.arange(8) #it will create array of elements from 0 to 7(end index-1)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [36]:
arnd = np.arange(10).reshape(5,2) # total 8 elements will be shaped into 2 rows and 5 columns
arnd

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [37]:
arnd = np.arange(8).reshape(2,4) # total 8 elements required - here only 6 elements are there
arnd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
arnd = np.arange(6).reshape(3,2)
arnd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [39]:
x = np.array([[1,2],[3,4]]) #x = np.array([1,2,3,4]
y = np.array([[3,5],[1,4]])
#array x contains two lists: [1, 2] and [3, 4].
#The first list [1, 2] becomes the first row of the matrix.
#The second list [3, 4] becomes the second row of the matrix.

print(x)
print(y)

[[1 2]
 [3 4]]
[[3 5]
 [1 4]]


In [40]:
x+y #element-wise addition between the two matrices x and y,adding the corresponding elements at the same position in both matrices
#1+3,2+5
#3+1,4+4

array([[4, 7],
       [4, 8]])

In [41]:
x-y

array([[-2, -3],
       [ 2,  0]])

In [42]:
x*y#this is not the correct matrix multiplication

array([[ 3, 10],
       [ 3, 16]])

In [43]:
#actual multiplication of matrices
np.dot(x,y)
'''[[1 2]  [[3 5]
   [3 4]]  [1 4]]
  '''
# dot product operation takes corresponding rows and columns from x and y, multiplies the elements, and sums them
#(1 * 3) + (2 * 1) = 3 + 2 = 5,(1 * 5) + (2 * 4) = 5 + 8 = 13
#(3 * 3) + (4 * 1) = 9 + 4 = 13,(3 * 5) + (4 * 4) = 15 + 16 = 31

'[[1 2]  [[3 5]\n   [3 4]]  [1 4]]\n  '

In [44]:
m = np.pi
#np.pi is a constant in the NumPy library that represents the mathematical constant π (pi).
m

3.141592653589793

In [45]:
a = np.array([0,30,60,90,120,150,180])
#This creates a NumPy array a that holds the angles in degrees
ar = a * np.pi/180
#ar array will contain the angles in radians
ar

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265])

In [46]:
print("sine value : ",np.sin(ar))
print("cosine value : ",np.cos(ar))
print("tangent value : ",np.tan(ar))

sine value :  [0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]
cosine value :  [ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]
tangent value :  [ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


In [47]:
np.exp(4) #e^x
# np.exp(x) is a function from the NumPy library that calculates the exponential of a given number

np.float64(54.598150033144236)

In [48]:
np.sqrt(4)

np.float64(2.0)

In [49]:
x=np.arange(10)
x
#np.sqrt(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
print(np.mean(x))#Returns the mean (average) of the array.(45/10)
print(np.median(x))#Returns the median (middle value) of the array.(4+5)/2
print(np.var(x))#Returns the variance, which tells us how spread out the numbers are around the mean
print(np.std(x))#Returns the standard deviation, which tells us how much the numbers deviate from the mean on average.

4.5
4.5
8.25
2.8722813232690143


In [51]:
x=np.arange(5) ** 2 #for each element in the array [0, 1, 2, 3, 4], we are squaring each element
#0^2,1^2,2^2,3^2,4^2
x

array([ 0,  1,  4,  9, 16])

In [52]:
np.power(2,3)

np.int64(8)

In [53]:
y=np.append(x,20)#np.append() is a function in NumPy used to add (append) values to the end of an existing array.
#20 is the value that you want to append to the array x
y

array([ 0,  1,  4,  9, 16, 20])

In [54]:
y=np.insert(x,2,30)#np.insert() is a NumPy function that allows you to insert values at specific positions in an array.
#value 30 is inserted at index 2
y

array([ 0,  1, 30,  4,  9, 16])

In [55]:
z=np.sort(y) #np.sort() is a NumPy function used to sort an array in ascending order.
z

array([ 0,  1,  4,  9, 16, 30])

In [56]:
z[::-1] # it reverses the array z

array([30, 16,  9,  4,  1,  0])

In [57]:
mat2 = np.zeros([5,5]) #np.zeros() is a function in NumPy used to create an array filled with zeros
#The parameter [5, 5] specifies the shape of the array. In this case, it's a 2-dimensional array with 5 rows and 5 columns (i.e., a 5x5 matrix).
print(mat2)
#resulting array is a 5x5 array filled with zeros.

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [60]:
random_num = np.random.randint(1,11) #generate anyone random integer value
#np.random.randint(low, high) is a function from the NumPy random module that generates a random integer.
#low is the inclusive lower bound (the smallest possible value).
#high is the exclusive upper bound (the largest possible value is one less than high).
#In this case, low = 1 and high = 11, so it generates a random integer between 1 and 10 (inclusive).
random_num

3

In [61]:
ran_float = np.random.rand() #generate random float value between 0 and 1
ran_float

0.02389117081166625

In [63]:
ran_float_range=np.random.uniform(1,5)#generate random float value between 1 to 5
ran_float_range

4.413700818470385

In [64]:
#generate random numbers from normal distribution with mean 0 and standard deviation 1
rnd = np.random.normal(0,1,size=(3,3))
#np.random.normal() is a function from the NumPy random module that generates random numbers from a normal (Gaussian) distribution
#loc: The mean (center) of the distribution. In this case, it's 0. This means the distribution is centered around 0.
#scale: The standard deviation (spread or width) of the distribution. Here, it's 1. This means the spread is based on a standard normal distribution (i.e., a normal distribution with a mean of 0 and a standard deviation of 1).
#size: The shape of the output array. Here, it's (3, 3), meaning a 3x3 matrix (a 2D array with 3 rows and 3 columns) will be created.
rnd

array([[ 1.68345384, -0.76687228, -0.0409674 ],
       [-0.43989028,  0.29425093,  0.73772674],
       [-0.33571751, -0.35286031, -0.4700335 ]])

In [67]:
np.random.seed(4)
#np.random.seed() is used to set the seed for the random number generator in NumPy
#The seed is a starting point for generating a sequence of random numbers. 
#By setting the seed to a fixed number (in this case, 4), you ensure that the random numbers generated will be reproducible. This means every time you run the code with the same seed (4), you will get the same sequence of random numbers.
rnd = np.random.rand(3)
rnd

array([0.96702984, 0.54723225, 0.97268436])

In [68]:
rand_vec = np.random.randn(15)
#np.random.randn() generates random numbers from the standard normal distribution, meaning the numbers follow a normal distribution with a mean of 0 and a standard deviation of 1.
#The argument 15 specifies that we want to generate 15 random values from this normal distribution.
print(rand_vec)
##The resulting rand_vec is a 1D NumPy array of 15 random floating-point values drawn from the standard normal distribution. These values can be both positive and negative.
print()
print(rand_vec>0)#rand_vec > 0 creates a boolean mask or boolean array.False if <0 and True if >0

[ 0.9934697   1.07932256  1.45162561 -0.33881198  0.36623181 -0.30501214
 -0.48492332 -0.12066567 -0.0788265   0.56373477 -0.18040236  0.20218012
  0.16951775 -0.71522547  0.52533388]

[ True  True  True False  True False False False False  True False  True
  True False  True]


In [70]:
rand_vec = np.random.randn(19)

print(rand_vec)

print()
print(rand_vec[11])#This prints the value located at index 6 of the array rand_vec
#rand_vec[6] accesses the element at the 10th position (index 6) of the array

[ 0.82448138  0.26043704  1.37718202 -1.37307059 -0.00993354 -1.38947805
  1.22956251 -0.25388263  0.85576984 -0.17599712 -1.69610226 -0.95617171
  1.15563935  0.24133141  0.27677085  1.04420738  0.18173901 -0.77604419
  0.82242392]

-0.9561717089896864


In [71]:
rand_mat4 = np.random.rand(5,5) # uniform random variable
#function np.random.rand() can take dimensions as arguments. Here, the arguments (5,5) specify the shape of the output array
#5x5 matrix 
print(rand_mat4)

[[0.89465129 0.51473397 0.60356351 0.06506781 0.54007473]
 [0.12918678 0.61456285 0.36365035 0.76775803 0.04853414]
 [0.10981812 0.68402322 0.5146537  0.57164137 0.84370699]
 [0.48773764 0.81014442 0.51024363 0.92672069 0.66692777]
 [0.14872684 0.36455318 0.86577492 0.35028521 0.18902576]]
